.PHONY: ex00 ex01 ex02

PY = python3

ex00:
	@python3 $@/test.py

ex01:
	@python3 $@/test.py

ex02:
	@python3 

style:
	python3 -m pycodestyle .
	@echo "\033[32mstyle test passed successfully\033[0m"

tost:
	python3 -m black .
