.PHONY: ex00 ex01 ex02

PY = python3

ex00:
	$(PY) $@/energy.py

ex01:
	$(PY) $@/personality.py

ex02:
	$(PY) $@/pressure.py

style:
	$(PY) -m pycodestyle .
	@echo "\033[32mstyle test passed successfully\033[0m"
